1559739227695	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559741130772	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559741131697	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559741131701	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559741132503	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559743057157	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559743057256	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559743057256	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559743057759	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559743058188	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559743058188	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559743058189	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559743058698	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559743058878	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559743058878	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559743058880	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559743058880	Sync.Service	INFO	Starting sync at 2019-06-05 15:57:38 in browser session DLDB2kz0MYXZ
1559743058880	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559743058885	Sync.Status	INFO	Resetting Status.
1559743058885	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559743058893	Sync.BrowserIDManager	INFO	Getting keys
1559743058893	Sync.BrowserIDManager	INFO	Getting an assertion from: https://token.services.mozilla.com/1.0/sync/1.5
1559743058893	FirefoxAccounts	DEBUG	enter getAssertion()
1559743058894	FirefoxAccounts	DEBUG	getCertificateSigned: true true
1559743058903	Services.Common.RESTRequest	TRACE	local time, offset: 1559743058903, 2970
1559743058911	Services.Common.RESTRequest	DEBUG	POST request to https://api.accounts.firefox.com/v1/certificate/sign
1559743058911	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1559743058911	Services.Common.RESTRequest	TRACE	HTTP Header content-type: application/json
1559743058911	Services.Common.RESTRequest	TRACE	HTTP Header accept-language: de,en-us,en
1559743058911	Services.Common.RESTRequest	DEBUG	POST Length: 888
1559743058911	Services.Common.RESTRequest	TRACE	POST Body: {"publicKey":{"algorithm":"DS","y":"1407DE43D666BC042F5732E090280C4D00DDA807672424338C274FDB93EDE367A24DD03A9E0FB908B278ACBCB3CA10288C7A07C8241A06BBECACD29164B40A72976F66509E01971D0F813E73F37E13FEE12E3DAFCD2EE9DF7EF33FACDDE659D8F1C8E3E7C3DFFAD8D9A81888E007122FAA9053A8F57EF1DC52BA4903C9EA0400","p":"FF600483DB6ABFC5B45EAB78594B3533D550D9F1BF2A992A7A8DAA6DC34F8045AD4E6E0C429D334EEEAAEFD7E23D4810BE00E4CC1492CBA325BA81FF2D5A5B305A8D17EB3BF4A06A349D392E00D329744A5179380344E82A18C47933438F891E22AEEF812D69C8F75E326CB70EA000C3F776DFDBD604638C2EF717FC26D02E17","q":"E21E04F911D1ED7991008ECAAB3BF775984309C3","g":"C52A4A0FF3B7E61FDF1867CE84138369A6154F4AFA92966E3C827E25CFA6CF508B90E5DE419E1337E07A2E9E2A3CD5DEA704D175F8EBF6AF397D69E110B96AFB17C7A03259329E4829B0D03BBC7896B15B4ADE53E130858CC34D96269AA89041F409136C7242A38895C9D5BCCAD4F389AF1D7A4BD1398BD072DFFA896233397A"},"duration":21600000}
1559743060100	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559743111278	Services.Common.RESTRequest	TRACE	onStartRequest: POST https://api.accounts.firefox.com/v1/certificate/sign
1559743111278	Services.Common.RESTRequest	TRACE	Channel for POST https://api.accounts.firefox.com/v1/certificate/sign returned status code 2152398862
1559743111278	Services.Common.RESTRequest	DEBUG	POST https://api.accounts.firefox.com/v1/certificate/sign failed: 2152398862 - NS_ERROR_NET_TIMEOUT
1559743111278	Services.Common.RESTRequest	TRACE	POST body: 
1559743111278	Hawk	WARN	hawk request error: [Exception... "NS_ERROR_NET_TIMEOUT"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "JS frame :: resource://services-common/rest.js :: onStopRequest :: line 434"  data: no] Stack trace: onStopRequest()@resource://services-common/rest.js:434
1559743111278	Services.Common.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: get status :: line 558"  data: no] Stack trace: get status()@resource://services-common/rest.js:558
request()@resource://services-common/hawkclient.js:224
1559743111278	Services.Common.RESTResponse	DEBUG	Caught exception fetching HTTP status text: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: get statusText :: line 573"  data: no] Stack trace: get statusText()@resource://services-common/rest.js:573
request()@resource://services-common/hawkclient.js:227
1559743111278	Hawk	DEBUG	(Response) /certificate/sign: code: null - Status text: null
1559743111278	Services.Common.RESTResponse	TRACE	Processing response headers.
1559743111278	Services.Common.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: get headers :: line 605"  data: no] Stack trace: get headers()@resource://services-common/rest.js:605
_maybeNotifyBackoff()@resource://services-common/hawkclient.js:288
request()@resource://services-common/hawkclient.js:234
1559743111278	Services.Common.RESTResponse	TRACE	Processing response headers.
1559743111278	Services.Common.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: get headers :: line 605"  data: no] Stack trace: get headers()@resource://services-common/rest.js:605
_maybeNotifyBackoff()@resource://services-common/hawkclient.js:288
request()@resource://services-common/hawkclient.js:235
1559743111278	Services.Common.RESTResponse	DEBUG	Caught exception fetching HTTP status text: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: get statusText :: line 573"  data: no] Stack trace: get statusText()@resource://services-common/rest.js:573
_constructError()@resource://services-common/hawkclient.js:116
request()@resource://services-common/hawkclient.js:240
1559743111278	Services.Common.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: get status :: line 558"  data: no] Stack trace: get status()@resource://services-common/rest.js:558
_constructError()@resource://services-common/hawkclient.js:117
request()@resource://services-common/hawkclient.js:240
1559743111278	Services.Common.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: get status :: line 558"  data: no] Stack trace: get status()@resource://services-common/rest.js:558
_constructError()@resource://services-common/hawkclient.js:118
request()@resource://services-common/hawkclient.js:240
1559743111278	Services.Common.RESTResponse	TRACE	Processing response headers.
1559743111278	Services.Common.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: get headers :: line 605"  data: no] Stack trace: get headers()@resource://services-common/rest.js:605
_constructError()@resource://services-common/hawkclient.js:123
request()@resource://services-common/hawkclient.js:240
1559743111278	FirefoxAccounts	ERROR	error POSTing /certificate/sign: {"error":{},"errorString":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 434\"  data: no]","message":null,"code":null,"errno":null}
1559743111278	FirefoxAccounts	ERROR	HAWK.signCertificate error: {"error":{},"errorString":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 434\"  data: no]","message":null,"code":null,"errno":null}
1559743111278	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: {"error":{},"errorString":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 434\"  data: no]","message":null,"code":null,"errno":null}
1559743111279	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1559743111279	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1559743111279	Sync.BrowserIDManager	ERROR	Failed to fetch a token for authentication: {"error":{},"errorString":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 434\"  data: no]","message":null,"code":null,"errno":null}
1559743111280	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1559743111280	FirefoxAccounts	DEBUG	getOAuthToken enter
1559743111281	FirefoxAccounts	TRACE	getCachedToken returning cached token
1559743111281	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1559743111281	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1559743111281	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1559743111281	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1559743111281	Services.Common.RESTRequest	TRACE	HTTP Header if-none-match: "1d3cb6698a7af7b246a9837b970c1e724afce599-gzip"
1559744974062	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559744974246	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559744974246	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559744974247	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559744974247	Sync.Service	INFO	Starting sync at 2019-06-05 16:29:34 in browser session DLDB2kz0MYXZ
1559744974248	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559744974248	Sync.Service	INFO	Cannot start sync: already syncing?
1559744974752	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559744975199	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559744975199	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559744975199	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559744975692	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559744976268	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559744976268	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559744976277	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559744976277	Sync.Service	INFO	Starting sync at 2019-06-05 16:29:36 in browser session DLDB2kz0MYXZ
1559744976277	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559744976277	Sync.Service	INFO	Cannot start sync: already syncing?
1559744983032	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559746903106	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559746903253	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559746903254	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559746903254	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559746903254	Sync.Service	INFO	Starting sync at 2019-06-05 17:01:43 in browser session DLDB2kz0MYXZ
1559746903255	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559746903255	Sync.Service	INFO	Cannot start sync: already syncing?
1559746903763	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559746904142	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559746904142	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559746904143	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559746904688	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559746905154	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559746905154	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559746905157	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559746905159	Sync.Service	INFO	Starting sync at 2019-06-05 17:01:45 in browser session DLDB2kz0MYXZ
1559746905164	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559746905164	Sync.Service	INFO	Cannot start sync: already syncing?
1559746906174	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559748812769	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559748813694	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559748813699	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559748815091	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559750713085	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559750713479	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559750713479	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559750713761	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559750714476	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559750714476	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559750714477	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559750714690	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559750715324	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559750715324	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559750715327	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559750715329	Sync.Service	INFO	Starting sync at 2019-06-05 18:05:15 in browser session DLDB2kz0MYXZ
1559750715330	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559750715331	Sync.Service	INFO	Cannot start sync: already syncing?
1559750716004	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559752606101	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559752606248	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559752606248	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559752606249	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559752606249	Sync.Service	INFO	Starting sync at 2019-06-05 18:36:46 in browser session DLDB2kz0MYXZ
1559752606249	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559752606250	Sync.Service	INFO	Cannot start sync: already syncing?
1559752606755	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559752607189	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559752607189	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559752607189	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559752607708	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559752608202	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559752608202	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559752608205	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559752608208	Sync.Service	INFO	Starting sync at 2019-06-05 18:36:48 in browser session DLDB2kz0MYXZ
1559752608211	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559752608211	Sync.Service	INFO	Cannot start sync: already syncing?
1559752609102	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559754538106	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559754538252	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559754538252	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559754538253	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559754538254	Sync.Service	INFO	Starting sync at 2019-06-05 19:08:58 in browser session DLDB2kz0MYXZ
1559754538254	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559754538255	Sync.Service	INFO	Cannot start sync: already syncing?
1559754538757	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559754539019	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559754539020	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559754539020	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559754539775	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559754539780	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559754540037	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559754540037	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559754540038	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559754540038	Sync.Service	INFO	Starting sync at 2019-06-05 19:09:00 in browser session DLDB2kz0MYXZ
1559754540039	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559754540039	Sync.Service	INFO	Cannot start sync: already syncing?
1559756471764	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559756472687	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559756474103	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559758358769	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559758359709	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559758359711	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559758360914	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559760255202	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559760255268	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559760255268	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559760255750	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559760256183	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559760256184	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559760256185	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559760256688	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559760257066	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559760257066	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559760257068	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559760257068	Sync.Service	INFO	Starting sync at 2019-06-05 20:44:17 in browser session DLDB2kz0MYXZ
1559760257072	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559760257073	Sync.Service	INFO	Cannot start sync: already syncing?
1559760258145	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559762175136	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559762175282	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559762175282	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559762175283	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559762175283	Sync.Service	INFO	Starting sync at 2019-06-05 21:16:15 in browser session DLDB2kz0MYXZ
1559762175284	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559762175284	Sync.Service	INFO	Cannot start sync: already syncing?
1559762175816	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559762176089	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559762176090	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559762176091	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559762176613	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559762176698	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559762176823	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559762176823	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559762176825	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559762176825	Sync.Service	INFO	Starting sync at 2019-06-05 21:16:16 in browser session DLDB2kz0MYXZ
1559762176831	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559762176831	Sync.Service	INFO	Cannot start sync: already syncing?
1559764080106	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559764080247	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559764080247	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559764080247	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559764080247	Sync.Service	INFO	Starting sync at 2019-06-05 21:48:00 in browser session DLDB2kz0MYXZ
1559764080248	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559764080248	Sync.Service	INFO	Cannot start sync: already syncing?
1559764080761	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559764080958	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559764080958	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559764080959	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559764081694	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559764082396	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559764082396	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559764082398	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559764082398	Sync.Service	INFO	Starting sync at 2019-06-05 21:48:02 in browser session DLDB2kz0MYXZ
1559764082402	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559764082403	Sync.Service	INFO	Cannot start sync: already syncing?
1559764083162	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559765980110	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559765980260	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559765980260	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559765980261	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559765980261	Sync.Service	INFO	Starting sync at 2019-06-05 22:19:40 in browser session DLDB2kz0MYXZ
1559765980261	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559765980261	Sync.Service	INFO	Cannot start sync: already syncing?
1559765980773	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559765980803	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559765980804	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1559765980804	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1559765980804	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559765980804	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559765980814	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
