1559805777789	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559807667208	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559807667306	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559807667306	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559807667307	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559807667307	Sync.Service	INFO	Starting sync at 2019-06-06 09:54:27 in browser session DLDB2kz0MYXZ
1559807667307	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559807667319	Sync.Status	INFO	Resetting Status.
1559807667319	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559807667752	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559807668183	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559807668183	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559807668184	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559807668687	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559807668831	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559807668831	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559807668834	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559807668842	Sync.Service	INFO	Starting sync at 2019-06-06 09:54:28 in browser session DLDB2kz0MYXZ
1559807668847	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559807668848	Sync.Service	INFO	Cannot start sync: already syncing?
1559807670084	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559809593763	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559809594692	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559809594696	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559809594699	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559809594699	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1559809594699	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1559809594699	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559809594700	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559809594701	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
