1559897547756	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559898500970	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559898501382	Sync.SyncScheduler	DEBUG	Woke from sleep.
1559898501383	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1559898501383	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1559898501384	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559898501487	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559898501487	Sync.Service	INFO	Starting sync at 2019-06-07 11:08:21 in browser session DLDB2kz0MYXZ
1559898501488	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559898501489	Sync.Status	INFO	Resetting Status.
1559898501490	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559898505718	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559898505885	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559898505885	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559898505886	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559898505886	Sync.Service	INFO	Starting sync at 2019-06-07 11:08:25 in browser session DLDB2kz0MYXZ
1559898505886	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559898505886	Sync.Service	INFO	Cannot start sync: already syncing?
1559898510868	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections?v=1.69.0 failed: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1559898510869	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1559898510869	Sync.SyncScheduler	DEBUG	Next sync in 90000 ms. (why=reschedule)
1559898510874	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
