1559682172263	Sync.LogManager	DEBUG	Flushing file log
1559682172304	Sync.LogManager	DEBUG	Log cleanup threshold time: 1558818172304
1559682172368	Sync.LogManager	DEBUG	Done deleting files.
1559684090062	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559684090316	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559684090316	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559684090317	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559684090317	Sync.Service	INFO	Starting sync at 2019-06-04 23:34:50 in browser session DLDB2kz0MYXZ
1559684090317	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559684090320	Sync.Status	INFO	Resetting Status.
1559684090320	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559684090761	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559684091315	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559684091316	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559684091316	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559684091690	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559684092319	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559684092319	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559684092321	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559684092321	Sync.Service	INFO	Starting sync at 2019-06-04 23:34:52 in browser session DLDB2kz0MYXZ
1559684092325	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559684092325	Sync.Service	INFO	Cannot start sync: already syncing?
1559684093110	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559686002299	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559686002299	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559686002353	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559686002354	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559686002354	Sync.Service	INFO	Starting sync at 2019-06-05 00:06:42 in browser session DLDB2kz0MYXZ
1559686002354	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559686002354	Sync.Service	INFO	Cannot start sync: already syncing?
1559686002801	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559686003538	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559686003538	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559686003539	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559686003693	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559686004262	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559686004262	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559686004264	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559686004264	Sync.Service	INFO	Starting sync at 2019-06-05 00:06:44 in browser session DLDB2kz0MYXZ
1559686004267	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559686004267	Sync.Service	INFO	Cannot start sync: already syncing?
1559686005115	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559686007972	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559686007972	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1559686007972	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1559686007973	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559686007973	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559686007977	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
