1559841945567	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559843822259	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559843822323	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559843822323	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559843822326	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559843822326	Sync.Service	INFO	Starting sync at 2019-06-06 19:57:02 in browser session DLDB2kz0MYXZ
1559843822326	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559843822329	Sync.Status	INFO	Resetting Status.
1559843822329	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559843822803	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559843823193	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559843823193	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559843823193	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559843823689	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559843824048	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559843824048	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559843824049	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559843824049	Sync.Service	INFO	Starting sync at 2019-06-06 19:57:04 in browser session DLDB2kz0MYXZ
1559843824054	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559843824054	Sync.Service	INFO	Cannot start sync: already syncing?
1559843825118	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559845756191	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559845756287	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559845756287	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559845756288	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559845756288	Sync.Service	INFO	Starting sync at 2019-06-06 20:29:16 in browser session DLDB2kz0MYXZ
1559845756288	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559845756288	Sync.Service	INFO	Cannot start sync: already syncing?
1559845756773	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559845757213	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559845757213	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559845757213	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559845757682	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559845758192	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559845758192	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559845758193	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559845758193	Sync.Service	INFO	Starting sync at 2019-06-06 20:29:18 in browser session DLDB2kz0MYXZ
1559845758198	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559845758198	Sync.Service	INFO	Cannot start sync: already syncing?
1559845759116	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559845761344	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559845761344	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1559845761344	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1559845761344	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559845761344	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559845761346	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
